apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
        - name: operator
          image: mock-operator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
